=== KnowledgeCaptureAndDiscovery/ikcap_site/nlg/isd-publications.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XML Spy v3.5 (http://www.xmlspy.com)-->
<xsd:schema xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" elementFormDefault="qualified">
	<xsd:element name="publications">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="publication" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="title" type="xsd:string"/>
							<xsd:element name="url" minOccurs="0" type="xsd:uriReference"/>
							<xsd:element name="person" type="xsd:string" maxOccurs="unbounded"/>
							<xsd:element name="project">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:enumeration value="Inspect"/>
										<xsd:enumeration value="Rosetta"/>
										<xsd:enumeration value="Temple"/>
										<xsd:enumeration value="Trellis"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== KnowledgeCaptureAndDiscovery/ikcap_site/kanal/isd-publications.xml
<!-- ISD Publications File -->
<!-- <?xml version="1.0" ?> -->
<publications xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation = "isd-publications.xsd">                                                         
  <publication>
    <title>
      "Knowledge Mobility: Semantics for the Web as a White Knight for Knowledge-Based Systems"
	 </title>
    <url>http://www.isi.edu/expect/papers/gil-seweb-book-01.pdf</url>
    <person>Yolanda Gil</person>
	 <where>"Developing the Semantic Web", D.Fensel, J. Hendler, H. Lieberman, W. Whalster(Eds), MIT Press, forthcoming
	 </where>
    <project>Trellis</project>
  </publication>
  <publication>
    <title>
      "Trellis: An Interactive Tool for Capturing Information Analysis and Decision Making"
	 </title>
    <url>http://www.isi.edu/expect/web/trellis/Trellis-8-01.pdf</url>
    <person>Yolanda Gil</person>
    <person>Varun Ratnakar</person>
    <project>Trellis</project>
  </publication>
  <publication>
    <title>"INSPECT: an Intelligent System for Air Campaign Plan Evaluation based on EXPECT"</title>
    <url>http://www.isi.edu/expect/inspect/inspect.html</url>
    <person>Valente, A.</person>
    <person>Gil, Y.</person>
    <person>Swartout, W. R.</person>
    <project>Inspect</project>
  </publication>
  <publication>
    <title>"A Representation and Library for Objectives in Air Campaign Plans"</title>
    <url>http://www.isi.edu/expect/grammar/grammar.html</url>
    <person>Valente, A.</person>
    <person>Swartout, W. R.</person>
    <person>Gil, Y.</person>
    <project>Inspect</project>
  </publication>
  <publication>
    <title>"A Representation for Measures of Effect in Air Campaign Plans"</title>
    <url>http://www.isi.edu/expect/measures-of-merit/mom-grammar.html</url>
    <person>Valente, A. </person>
    <project>Inspect</project>
  </publication>
  <publication>
    <title>"Integrating Expectations from Different Sources to Help End Users Acquire Procedural Knowledge",
     IJCAI 01</title>
    <url>http://www.isi.edu/expect/papers/blythe-ijcai01.pdf</url>
    <person>Blythe, J.</person>
    <project>Temple</project>
  </publication>
  <publication>
    <title>"An Integrated Environment for Knowledge Acquisition", Best Paper, International Conference
     on Intelligent User Interfaces, 2001</title>
    <url>http://www.isi.edu/expect/papers/blythe-kim-rama-gil-iui01.pdf</url>
    <person>Blythe, J. et al</person>
    <project>Temple</project>
    <project>Kasper</project>
  </publication>
  <publication>
    <title>"OntoMorph: A Translation System for Symbolic Knowledge" In Proceedings of the Seventh
     International Conference on Principles of Knowledge Representation and Reasoning (KR-2000),
     Breckenridge, CO, April 2000</title>
    <person>Chalupsky, H.</person>
    <project>Rosetta</project>
  </publication>
  <publication>
    <title>"Supporting Translation Among Planning Agents" (internal project report, in preparation)</title>
    <person>Blythe, J.</person>
    <person>Gil, Y.</person>
    <person>Chalupsky, H.</person>
    <person>MacGregor, R.</person>
    <project>Rosetta</project>
  </publication>
  <publication>
    <title>"PLANET: A Shareable and Reusable Ontology for Representing Plans", AAAI-2000 Workshop on
     Representational Issues for Real-World Planning Systems, Austin, TX, July 2000</title>
    <person>Gil, Y.</person>
    <person>Blythe, J.</person>
    <project>Rosetta</project>
  </publication>
  <publication>
    <title>"An Analysis of the CoABS TIE-1 Messages: Opportunities and Challenges for Agent Translation
     Services" (in preparation)</title>
    <person>Gil, Y.</person>
    <project>Rosetta</project>
  </publication>

  <publication>
    <title>"Knowledge Analysis on Process Models"</title>
    <person>Kim, J.</person>
    <person>Gil, Y.</person>
    <project>Kasper</project>
    <project>KANAL</project>
    <where>"Seventeenth International Joint Conference on Artificial
                                  Intelligence" (IJCAI-01)
    </where>
  </publication>
  <publication>
    <title>"Knowledge Analysis on Process Models"</title>
    <person>Kim, J.</person>
    <person>Gil, Y.</person>
    <project>Kasper</project>
    <project>KANAL</project>
    <where>"Seventeenth International Joint Conference on Artificial
                                  Intelligence" (IJCAI-01)
    </where>
  </publication>

  <publication>
    <title>"Acquiring Problem-Solving Knowledge from
   End Users: Putting Interdependency Models to the Test"</title>
    <person>Kim, J.</person>
    <person>Gil, Y.</person>
    <project>Kasper</project>
    <project>EMeD</project>
    <where>"Seventeenth National Conference on Artificial Intelligence" (AAAI-00)
    </where>
  </publication>

  <publication>
    <title>"User Studies of an Interdependency-Based
   Interface for Acquiring Problem-Solving Knowledge"</title>
    <person>Kim, J.</person>
    <person>Gil, Y.</person>
    <project>HPKB</project>
    <project>EMeD</project>
    <where>"Intelligent User Interface Conference 2000." (IUI-00)
    </where>
  </publication>

  <publication>
    <title>" Deriving Expectations to Guide Knowledge Base
   Creation"</title>
    <person>Kim, J.</person>
    <person>Gil, Y.</person>
    <project>HPKB</project>
    <project>EMeD</project>
    <where>"Sixteenth National Conference on Artificial
   Intelligence." (AAAI-99)
    </where>
  </publication>


</publications>
